#!/bin/bash
set -ex

pwd;
BRANCH="$1";

# Validate branch name
if [[ ! "$BRANCH" =~ ^(?:revert-\d+-)?(?:fix|hotfix|feat|docs|style|refactor|perf|test)\/[A-Z]+-\d+-[a-zA-Z0-9-._]+$ ]]; then
    echo "Invalid branch name. It should follow the pattern <type>/<scope>-<description>"
    echo "Type: fix | hotfix | feat | docs | style | refactor | perf | test"
    echo "Scope: UPPERCASE Project Key + Ticket Number (e.g., CNV-123)"
    echo "Description: lowercase, hyphen-separated words"
    exit 1
fi

git checkout master;

# Create a new branch from master if it doesn't exist.
if [ "`git branch --list ${BRANCH}`" ]; then
    git checkout -f $BRANCH
    git clean -fd -f
    git reset --hard
else
    git branch $BRANCH
    git checkout -f $BRANCH
fi
