#!/bin/bash
set -ex

pwd;
BRANCH="$1";

git checkout master;

# Create a new branch from master from master if it doesn't exists.
if [ "`git branch --list ${BRANCH}`" ]; then
    git checkout -f $BRANCH
    git clean -fd -f
    git reset --hard
else
    git branch $BRANCH
    git checkout -f $BRANCH
fi
